### PR TITLE
Partialstyling

### PR DESCRIPTION
**Pull request by abby-wilson**

### CODE REVIEW

**Comment by maryfranks** [comment]
It look amazing but for some reason on my browser the div for Plan a Trip (with the map photo) is slightly larger than the others.

**Comment by maryfranks** [comment]
and I just noticed in the footer is says "contat us" instead of contact us :)

**Comment by abby-wilson** [comment]
Yeah I've just seen that will sort it tomorrow :)

**Comment by martinegagne** [comment]
sweeeeeet!

**Pull request merged**
