### PR TITLE
Msc tasks

### PR DESCRIPTION
**Pull request by maryfranks**
Fixes bug in trips.js: now you can add messages via ajax request.  Adds edit button to trip show page and redirects after successful save back to trip show page.  Reconfigures messages to use strong params (to dos doesn't need one).  Sorts the parks alphabetically on the parks index page.

### CODE REVIEW

**Comment by abby-wilson** [comment]
<3 <3 <3 <3

**Comment by martinegagne** [comment]
Hey Mary! Went through the functionality of the messages on the show page. Can add a message, delete a message, but there's a bug when editing a message. 

Also - under "Trip ToDos" on the trip show page, the trip id number is showing up. 

Everything else looks good though!

**Comment by nadiaivannova** [comment]
went through code with martine... see her comments :)

**Comment by maryfranks** [comment]
Bug fixed!  I just needed to change the path where the partial was rendered in the edit view

**Pull request merged**
